### ISSUE TITLE
Feature request: add a filter for fade-in animation

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/crazy-lazy#10]
The fade in animation of images loaded is hard coded to [200ms](https://github.com/pluginkollektiv/crazy-lazy/blob/master/js/jquery.unveil.js#L35). This could be made customizable via a PHP filter and `wp_localize_script()`.

See: https://wordpress.org/support/topic/fadein-animation

**Comment by 2ndkauboy** [comment]
Getting this feature to work with a filter seems not to be as easy as expected. I am going to review the new version of unveil.js and the "non-jquery" variant lazyload.js to get a consistent effect for both of them. An optimal solution would be a single JavaScript variant, no matter if jQuery is used or not. Using CSS effects rather than JavaScript animation might be an option.

So unfortunately, I cannot close this issue for current version and before WP 4.6 release.

**Comment by patrickrobrecht** [comment]
Closed due to EOL (#39)
