### ISSUE TITLE
Add option to skip specific pages

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/crazy-lazy#19]
First reported here: https://wordpress.org/support/topic/disable-lazy-loading-on-certain-page/

**Comment by Tobias-Keller** [comment]
Should we add a post meta, or a meta box?

post meta:
- not so user friendly (must be documented, like the single image exclude)
meta box with option:
- a extra meta box could be too much

**Comment by florianbrinkmann** [comment]
We will work on this and add a meta box (and maybe Gutenberg support).

**Comment by florianbrinkmann** [comment]
After thinking about it, that might not be a fix for the problem with the load more posts if the blog posts are displayed on the home page, because there would not be a publish meta box for that page. So it would be better to fix the issue with ajax loaded content instead/additionally.

Other possibility would be to add a text field for the page/post IDs to exclude. That would also be possible for the home page, but not very user-friendly.

**Comment by 2ndkauboy** [comment]
I would solve this by either adding a filter or setting on the "Settings -> Media" page. I really don't want to add a meta box or a whole settings page for Crazy Lazy for a feature, that is probably not being used by many users.

**Comment by patrickrobrecht** [comment]
Closed due to EOL (#39)
