### ISSUE TITLE
Add support for (media) widgets

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/crazy-lazy#20]
If I am correct Crazy Lazy just supports post content and post thumbnails:
https://github.com/pluginkollektiv/crazy-lazy/blob/2c265e16ccb9580bcc273a0a3dc8f4cf022c77a1/inc/crazy-lazy.class.php#L41-L56

Let's add support for (media) widgets.

We could use `widget_text`and `widget_{$this->id_base}_instance`(but I have no clue how the latter works ...)

**Comment by florianbrinkmann** [comment]
@Zodiac1978 I made a PR that adds support for text and HTML widgets. It’s not possible to add this for the image and gallery widget, because the `wp_get_attachment_image()` output cannot be filtered yet, and galleries in the text widget cannot be supported because there is no filter after the gallery shortcodes are parsed.

**Comment by Zodiac1978** [comment]
Related: https://core.trac.wordpress.org/ticket/27399

**Comment by Zodiac1978** [comment]
After reading the ticket I am hoping this could get fixed in core.

Additionally I ran across [comment 2](https://core.trac.wordpress.org/ticket/27399#comment:2) and think we could maybe add some more filter:
> "get_avatar", "post_thumbnail_html", "the_content" and "widget_text"

So what about lazy loading Avatars @florianbrinkmann?

**Comment by florianbrinkmann** [comment]
Added avatar support to #21 @Zodiac1978!
